name: virtualcell
channels:
    - defaults
    - conda-forge
dependencies:
    - mdtraj=1.9.4
    - openmm=7.4.0
    - python=3.7
    - pandas=1
    - scipy=1
    - matplotlib=3
    - numpy=1
    - jupyter
    - notebook
